CREATE USER JSP_APP IDENTIFIED BY JSP_APP;
GRANT CONNECT TO JSP_APP;
GRANT ALL PRIVILEGES to JSP_APP;
--------------------------------------------------------
--  File creato - sabato-novembre-29-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_IB_MPREST_DOCUMENTI
--------------------------------------------------------

  CREATE TABLE "JSP_APP"."T_IB_MPREST_DOCUMENTI" 
   (	"ID_PROPOSTA" NUMBER, 
	"TIPO_DOCUMENTO" VARCHAR2(1000 BYTE), 
	"STATO" VARCHAR2(1 BYTE), 
	"COD_GRUPPO" VARCHAR2(256 BYTE), 
	"NOME_FILE" VARCHAR2(2000 BYTE), 
	"DOCUMENTO" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DOCUMENTO") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table T_IB_MPREST_RIFIUTO
--------------------------------------------------------

  CREATE TABLE "JSP_APP"."T_IB_MPREST_RIFIUTO" 
   (	"CODICE_AUP" VARCHAR2(2000 BYTE), 
	"ID_PROPOSTA" NUMBER, 
	"RIFIUTO" VARCHAR2(150 BYTE), 
	"MOTIVO_RIFIUTO" VARCHAR2(2000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_IB_MPREST_STEP
--------------------------------------------------------

  CREATE TABLE "JSP_APP"."T_IB_MPREST_STEP" 
   (	"CODICE_AUP" VARCHAR2(2000 BYTE), 
	"COD_TIPO_DOCUMENTO" VARCHAR2(1000 BYTE), 
	"DATA_PRESA_VISIONE" DATE, 
	"TIPO_OPERAZIONE" CHAR(1 BYTE), 
	"CODICE_PROPOSTA" VARCHAR2(2000 BYTE), 
	"CODICE_SEZIONE" NUMBER, 
	"COD_BLOCCO" VARCHAR2(2 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_T_IB_MPREST_DOCUMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "JSP_APP"."PK_T_IB_MPREST_DOCUMENTO" ON "JSP_APP"."T_IB_MPREST_DOCUMENTI" ("ID_PROPOSTA", "TIPO_DOCUMENTO", "COD_GRUPPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_T_IB_MPREST_STEP
--------------------------------------------------------

  CREATE UNIQUE INDEX "JSP_APP"."PK_T_IB_MPREST_STEP" ON "JSP_APP"."T_IB_MPREST_STEP" ("CODICE_AUP", "COD_TIPO_DOCUMENTO", "TIPO_OPERAZIONE", "DATA_PRESA_VISIONE", "CODICE_SEZIONE", "COD_BLOCCO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_T_IB_MPREST_RIFIUTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "JSP_APP"."PK_T_IB_MPREST_RIFIUTO" ON "JSP_APP"."T_IB_MPREST_RIFIUTO" ("CODICE_AUP", "ID_PROPOSTA", "RIFIUTO", "MOTIVO_RIFIUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table T_IB_MPREST_RIFIUTO
--------------------------------------------------------

  ALTER TABLE "JSP_APP"."T_IB_MPREST_RIFIUTO" ADD CONSTRAINT "PK_T_IB_MPREST_RIFIUTO" PRIMARY KEY ("CODICE_AUP", "ID_PROPOSTA", "RIFIUTO", "MOTIVO_RIFIUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_RIFIUTO" MODIFY ("CODICE_AUP" NOT NULL ENABLE);
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_RIFIUTO" MODIFY ("ID_PROPOSTA" NOT NULL ENABLE);
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_RIFIUTO" MODIFY ("RIFIUTO" NOT NULL ENABLE);
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_RIFIUTO" MODIFY ("MOTIVO_RIFIUTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_IB_MPREST_STEP
--------------------------------------------------------

  ALTER TABLE "JSP_APP"."T_IB_MPREST_STEP" ADD CONSTRAINT "PK_T_IB_MPREST_STEP" PRIMARY KEY ("CODICE_AUP", "COD_TIPO_DOCUMENTO", "TIPO_OPERAZIONE", "DATA_PRESA_VISIONE", "CODICE_SEZIONE", "COD_BLOCCO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_STEP" MODIFY ("CODICE_AUP" NOT NULL ENABLE);
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_STEP" MODIFY ("COD_TIPO_DOCUMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_STEP" MODIFY ("DATA_PRESA_VISIONE" NOT NULL ENABLE);
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_STEP" MODIFY ("TIPO_OPERAZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_STEP" MODIFY ("CODICE_SEZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_STEP" MODIFY ("COD_BLOCCO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_IB_MPREST_DOCUMENTI
--------------------------------------------------------

  ALTER TABLE "JSP_APP"."T_IB_MPREST_DOCUMENTI" ADD CONSTRAINT "PK_T_IB_MPREST_DOCUMENTO" PRIMARY KEY ("ID_PROPOSTA", "TIPO_DOCUMENTO", "COD_GRUPPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_DOCUMENTI" MODIFY ("ID_PROPOSTA" NOT NULL ENABLE);
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_DOCUMENTI" MODIFY ("TIPO_DOCUMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_DOCUMENTI" MODIFY ("STATO" NOT NULL ENABLE);
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_DOCUMENTI" MODIFY ("COD_GRUPPO" NOT NULL ENABLE);
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_DOCUMENTI" MODIFY ("NOME_FILE" NOT NULL ENABLE);
 
  ALTER TABLE "JSP_APP"."T_IB_MPREST_DOCUMENTI" MODIFY ("DOCUMENTO" NOT NULL ENABLE);
